<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>man_mapping</name>
  <version>0.0.0</version>
  <description>manually control go2 and map the area</description>
  <maintainer email="russ2510@gmail.com">russ</maintainer>
  <license>TODO: License declaration</license>


  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>unitree_go</depend>
  <depend>std_msgs</depend>
  <depend>orocos_kdl</depend>
<depend>kdl_parser</depend>
<depend>urdf</depend>
   <!-- launch system -->
  <exec_depend>ros2launch</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <!-- python ROS node support -->
  <exec_depend>rclpy</exec_depend>

  <!-- add the packages you reference in your launch files -->
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>slam_toolbox</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>pointcloud_to_laserscan</exec_depend>
  <exec_depend>tf2_geometry_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
